# Run from the repository root:
#   hb_compile -c deploy/s100/actor_estimator_s100.yaml
model_parameters:
  onnx_model: './export/actor_estimator.onnx'
  march: 'nash-e'
  output_model_file_prefix: 'actor_estimator'
  working_dir: './hbm'

input_parameters:
  input_name: 'actor_obs;depth_latent'
  input_type_train: 'featuremap;featuremap'
  input_type_rt: 'featuremap;featuremap'
  input_shape: '1x753;1x32'

calibration_parameters:
  cal_data_dir: './calib/actor_estimator/actor_obs;./calib/actor_estimator/depth_latent'
  quant_config:
    model_config:
      all_node_type: 'int16'
      model_output_type: 'int16'
      modelwise_search:
        metric: 'chebyshev'
      layerwise_search:
        metric: 'chebyshev'
    node_config:
      '/estimator/estimator/estimator.0/Gemm':
        input1: 'ec'
      '/estimator/estimator/estimator.2/Gemm':
        input1: 'ec'
      '/estimator/estimator/estimator.4/Gemm':
        input1: 'ec'
      '/actor/history_encoder/encoder/encoder.0/Gemm':
        input1: 'ec'
      '/actor/history_encoder/conv_layers/conv_layers.0/Conv':
        input1: 'ec'
      '/actor/history_encoder/conv_layers/conv_layers.2/Conv':
        input1: 'ec'
      '/actor/history_encoder/linear_output/linear_output.0/Gemm':
        input1: 'ec'
      '/actor/actor_backbone/actor_backbone.0/Gemm':
        input1: 'ec'
      '/actor/actor_backbone/actor_backbone.2/Gemm':
        input1: 'ec'
      '/actor/actor_backbone/actor_backbone.4/Gemm':
        input1: 'ec'
      '/actor/actor_backbone/actor_backbone.6/Gemm':
        input1: 'int16'

compiler_parameters:
  compile_mode: 'latency'
  core_num: 1
  optimize_level: 'O2'
  input_source:
    actor_obs: 'ddr'
    depth_latent: 'ddr'
  max_l2m_size: 0
  extra_params:
    input_no_padding: true
    output_no_padding: true
