# Run from the repository root:
#   hb_compile -c deploy/s100/depth_encoder_s100.yaml
model_parameters:
  onnx_model: './export/depth_encoder.onnx'
  march: 'nash-e'
  output_model_file_prefix: 'depth_encoder'
  working_dir: './hbm'

input_parameters:
  input_name: 'depth_image;proprio;h_in'
  input_type_train: 'featuremap;featuremap;featuremap'
  input_type_rt: 'featuremap;featuremap;featuremap'
  input_shape: '1x58x87;1x53;1x1x512'

calibration_parameters:
  cal_data_dir: './calib/depth_encoder/depth_image;./calib/depth_encoder/proprio;./calib/depth_encoder/h_in'
  quant_config:
    model_config:
      all_node_type: 'int16'
      model_output_type: 'int16'
      modelwise_search:
        metric: 'chebyshev'
      layerwise_search:
        metric: 'chebyshev'
    node_config:
      '/base_backbone/image_compression/image_compression.0/Conv':
        input1: 'ec'
      '/base_backbone/image_compression/image_compression.3/Conv':
        input1: 'ec'
      '/base_backbone/image_compression/image_compression.6/Gemm':
        input1: 'ec'
      '/base_backbone/image_compression/image_compression.8/Gemm':
        input1: 'ec'
      '/combination_mlp/combination_mlp.0/Gemm':
        input1: 'ec'
      '/combination_mlp/combination_mlp.2/Gemm':
        input1: 'ec'
      '/rnn/GRU_split_to_forward_x_matmul_w0':
        input1: 'ec'
      '/rnn/GRU_split_to_forward_x_matmul_w1':
        input1: 'ec'
      '/rnn/GRU_split_to_forward_x_matmul_w2':
        input1: 'ec'
      '/rnn/GRU_split_to_forward_z0_h_matmul_r':
        input1: 'ec'
      '/rnn/GRU_split_to_forward_r0_h_matmul_r':
        input1: 'ec'
      '/rnn/GRU_split_to_forward_h0_h_matmul_r':
        input1: 'ec'
      '/output_mlp/output_mlp.0/Gemm':
        input1: 'ec'

compiler_parameters:
  compile_mode: 'latency'
  core_num: 1
  optimize_level: 'O2'
  input_source:
    depth_image: 'ddr'
    proprio: 'ddr'
    h_in: 'ddr'
  max_l2m_size: 0
  extra_params:
    input_no_padding: true
    output_no_padding: true
